{
 "title": "graphs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "data_leakage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "data_leakage_gap{job=\"fastapi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "traffic by http and method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_requests_total{job=\"fastapi\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"fastapi\", status=\"4xx\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"fastapi\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}