
services:
  fastapi:
    image: ghcr.io/althu123696/ipl-ii/fastapi:latest
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"

  streamlit:
    image: ghcr.io/althu123696/ipl-ii/streamlit:latest
    container_name: streamlit
    restart: always
    ports:
      - "8501:8501"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - fastapi

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - prometheus

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - mlflow-data:/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0

volumes:
  prometheus-data:
  grafana-data:
  mlflow-data:
