services:
  fastapi:
    image: ghcr.io/althu123696/ipl-ii/fastapi:latest
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"

  streamlit:
    image: ghcr.io/althu123696/ipl-ii/streamlit:latest
    container_name: streamlit
    restart: always
    ports:
      - "8501:8501"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
